### PR TITLE
fix bug: when isLTR = true, render incorrectly

### PR DESCRIPTION
**Pull request by daheeahn**
1. first row is isLTR = false
2. second row is isLTR = true

actual behavior
actual

expected behavior (fixed)
expected

### CODE REVIEW

**Comment by minhtc** [comment]
@daheeahn Thank you for the PR, have you pushd all the changed files?

**Comment by daheeahn** [comment]
yes!

**Comment by daheeahn** [comment]
But I didn't test it when it was vertical. This is the result of testing only when it is horizontal. Shall I test it when it is vertical?

**Comment by daheeahn** [comment]
and my code is

```
      <AutoScrolling
        style={{ height: 130 }}
        duration={15000}
        isVertical={false}
        endPaddingWidth={25}>
        <View>
          <MyCustomCircles ~~~ />        
        </View>
      </AutoScrolling>
      <AutoScrolling
        style={{ height: 130 }}
        duration={15000}
        isVertical={false}
        endPaddingWidth={25}
        isLTR={true}>
        <View>
          <MyCustomCircles ~~~ />        
        </View>
      </AutoScrolling>
```

**Comment by minhtc** [comment]
As i can see in the file changed, you just remove the codes that supports isLTR.
Please check our example here: https://snack.expo.io/@minhtc/react-native-auto-scrolling-demo

**Pull request closed without merging**
